### ISSUE TITLE
GobChat will not display any text or logs at all

### ISSUE THREAD

**Issue by pyrofishy23** [MarbleBag/Gobchat#60]
**Describe the bug**

I've used gobchat for several weeks just fine and then two days ago it abruptly broke out of nowhere. I didn't change or add anything, even any mods. it just stopped working. I can open it and it will say it's connected to FFXIV and even shows the connection icon in my tray, but when I type it won't display any logs of anything. 

**Expected behaviour**

It should display the text logs as I type.

**Actual behaviour**

Nothing happens at all. No text, nothing. It doesn't even give a log file. It's just a blank black text background and nothing else.

**Steps to reproduce**

1. Open Gobchat as normal
2. Try to type.
3. Nothing happens.

**Additional context**

I've done troubleshooting for just about everything I can think of and followed all the troubleshooting guides you have listed and nothing is working. I have all the chat types enabled and still nothing. I've tried with range filter on and off, still nothing. I've tried deleting the 'sharlayan' file and nothing. I've purged the entire program and all traces of it from my computer and reinstalled it and nothing. I've deleted and purged my computer of FFXIV and Gobchat and reinstalled both from scratch and still nothing. I'm at a loss for why it suddenly stopped working or how to get it to work again at this point.

**Comment by MarbleBag** [comment]
I had about two people with a similar issue in the past. In both cases the system clock was the culprit. Gobchat retrieves  the system time on startup and doesn't show any messages which are older than that.

If that's not the case and gobchat_debug.log  doesn't contain any error or helpful info messages, please open NLog.config and change the log level from `<logger name="*" minlevel="Info" writeTo="file" />` to `<logger name="*" minlevel="Debug" writeTo="file" />`
(You can find those files in the folder beside gobchat.exe)

That will put a lot more information into gobchat_debug.log, including the **content of your chat** and what it does with it. Maybe you can spot the error for yourself, otherwise I need that file. 

Sorry that it has taken me so long to answer.

**Comment by pyrofishy23** [comment]
I apologize this took so long to respond to as well. I sort of gave up hope and forgot to check back until a friend told me it was updated ;-;

Whatever was done with the latest update fixed the issue. Thank you so much.
