### ISSUE TITLE
Mentions Dysfunctional After Name Change

### ISSUE THREAD

**Issue by SomebodyAnxious** [MarbleBag/Gobchat#79]
I put all of my character's first names in my mentions, and normally, it detects that that is the name of the character I'm currently playing on and doesn't notify me. However, after I changed the last name of one of my characters, it stopped recognizing that character as me and began to notify me every time I say my own name.

Gobchat should recognize me as the same character after the name change and not notify me whenever I say my own name.

It continues to notify me as if I'm not the same character following the name change.

**Replication:**
1. Enter the first name of your character in "Mentions".
2. Change the name of your character.
3. Say your name in chat.
4. You will be notified mentioning yourself, even while "check own messages for mentions" is off.

I've tried resetting Gobchat by reinstalling it, but the issue persists.

**Comment by MarbleBag** [comment]
Error probably related to how the game treats capitalization after hyphens.

**Comment by SomebodyAnxious** [comment]
Is there a way to fix it?

**Comment by MarbleBag** [comment]
I thought this was fixed since 1.11.3, because the checkbox did indeed not work with hyphens in your character's name. If this is still present in 1.11.4, could you do some tests for me?

If so, please open the NLog.config file, any texteditor will do, and change the _info_ in line `<logger name="*" minlevel="Info" writeTo="file" />` to _debug?_
It should look like this: `<logger name="*" minlevel="debug" writeTo="file" />`

Gobchat will now log a lot more to `gobchat_debug.log`, among other things, chat messages and mentions.
I don't need much, type away some messages ingame, some with, some without mentions and some with the checkbox `Check own messages for mentions` set and some without. 
I don't mind if you replace the letters in your character's name (or others) with asterisks, but keep any special letters intact, like hyphens or apostrophes.
